export const RESET_SEARCH = "RESET_SEARCH";

export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";

export const SET_SEARCH_STATUS = "SET_SEARCH_STATUS";
export const PUSH_SEARCH_RESULTS = "PUSH_SEARCH_RESULTS";
export const INCREMENT_CURRENT_PAGE = "INCREMENT_CURRENT_PAGE";
export const DECREMENT_CURRENT_PAGE = "DECREMENT_CURRENT_PAGE";

export const SEARCH_IN_PROGRESS = "SEARCH_IN_PROGRESS";
export const GOT_NEXT_PAGE = "GOT_NEXT_PAGE";
export const GOT_PREV_PAGE = "GOT_PREV_PAGE";
export const NEXT_PAGE_CACHED = "NEXT_PAGE_CACHED";
export const CURRENT_PAGE_ITEMS = "CURRENT_PAGE_ITEMS";

export const GET_NEXT_PAGE = "GET_NEXT_PAGE";
export const GET_PREV_PAGE = "GET_PREV_PAGE";
export const GET_NEW_SEARCH = "GET_NEW_SEARCH";

export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

export const GET_PACKAGE_DETAILS = "GET_PACKAGE_DETAILS";

export const MODAL_VISIBILITY = "MODAL_VISIBILITY";
export const MODAL_INFO = "MODAL_INFO";

export const SET_MODAL_VISIBILITY = "SET_MODAL_VISIBILITY";
export const SET_MODAL_INFO = "SET_MODAL_INFO";
export const RESET_MODAL_INFO = "RESET_MODAL_INFO";
